// The parity contract with the Unreal build, owned by the repo that owns the
// source of truth.
//
// `landnam-ue` has had a C++ port of `src/rng` since
// 2026-08-10, with an automation test (`LandnamParityTest.cpp`) that checks
// it against a big file of golden vectors. That arrangement had one hole,
// and it is the exact hole a parity harness exists to close: the vectors
// were generated by a script that lived on one machine and was never
// committed HERE. So this repo — which owns the code the vectors describe —
// had no idea the contract existed. Change `src/rng.ts`, and the vectors go
// stale, and the Unreal test keeps passing against yesterday's expectations
// while the two builds quietly disagree. A green parity test that cannot
// see one side of the parity is worse than none, because it is reassuring.
//
// `port/golden.json` is now that file, committed here. This test recomputes
// every vector in it from the live `src/rng` and fails if any
// of them moved. The stored INPUTS are the spec and the stored OUTPUTS are
// the expectation, so the same file is both the thing Unreal asserts against
// and the thing this repo cannot drift from without being told.
//
// Workflow when a change here is deliberate: this test prints what moved,
// you regenerate (see port/rng.md), and you copy `port/golden.json` into the
// Unreal project at `Content/Data/golden.json`. Both sides move together or
// neither does.

import { describe, it, expect } from 'vitest';
import goldenText from '../port/golden.json?raw';
import { hashString, makeRng, makeSeedPhrase, stream, type Rng, type StreamName } from '../src/rng';

interface Golden {
  drawsPerStream: number;
  rng: {
    hashString: { text: string; hash: number }[];
    streams: {
      name: string;
      seed: string;
      nextRaw: number[];
      ints: number[];
      wideInts: number[];
      rolls: number[];
      chances: boolean[];
      floats: number[];
      shuffles: number[][];
      weights: number[];
      weighted: number[];
      derived: { label: string; seed: string; raw: number[] }[];
    }[];
    seedPhrases: { entropy: number; phrase: string }[];
  };
}

const golden = JSON.parse(goldenText) as Golden;

/** Doubles cross JSON, so compare at a tolerance far tighter than any drift. */
const TOL = 1e-9;
const near = (a: number, b: number) => Math.abs(a - b) <= TOL;

/** Collects every disagreement in a section rather than dying on the first. */
function section(name: string, run: (fail: (why: string) => void) => number): void {
  const failures: string[] = [];
  const checked = run((why) => failures.push(why));
  if (failures.length > 0 && (globalThis as { process?: { env: Record<string, string | undefined> } }).process?.env?.['LANDNAM_PARITY_VERBOSE']) {
    // eslint-disable-next-line no-console
    console.log(`PARITY ${name}:`, failures.slice(0, 12).join(' | '));
  }
  expect(checked, `${name}: no cases in the golden file`).toBeGreaterThan(0);
  expect(
    failures.slice(0, 6),
    `${name}: ${failures.length} of ${checked} vectors disagree with src/`,
  ).toEqual([]);
}

// --- The generator ---

/**
 * Every section draws from its OWN fresh generator on the stream's seed, and
 * then sequentially within itself. Recovered by solving against the committed
 * vectors rather than assumed — `wideInts` is `int(-50, 250)`, `floats` is
 * `float(-2.5, 7.5)` and `chances` is `chance(0.3)`, none of which the C++
 * could have told me, since the generating script was never in this repo.
 * (Solved, not guessed: the six streams together pin the chance probability
 * to (0.297557, 0.302485], and 0.3 is the only round number in it.)
 */
const SECTIONS = {
  ints: (r: Rng) => r.int(1, 6),
  wideInts: (r: Rng) => r.int(-50, 250),
  rolls: (r: Rng) => r.roll(2, 6),
  chances: (r: Rng) => r.chance(0.3),
  floats: (r: Rng) => r.float(-2.5, 7.5),
} as const;

describe('the rng port contract', () => {
  it('hashString', () => {
    section('rng.hashString', (fail) => {
      for (const c of golden.rng.hashString) {
        if (hashString(c.text) !== c.hash) fail(`hashString(${JSON.stringify(c.text)})`);
      }
      return golden.rng.hashString.length;
    });
  });

  it('every stream, draw for draw', () => {
    for (const s of golden.rng.streams) {
      section(`rng.${s.name}`, (fail) => {
        let checked = 0;
        // The stream seed itself is part of the contract: rename a stream and
        // every existing seed builds a different world.
        const seed = 'raven-skerry-317';
        if (`${seed}#${s.name}` !== s.seed) fail(`stream seed for ${s.name} is ${s.seed}`);

        const fresh = () => stream(seed, s.name as StreamName);

        const raw = fresh();
        s.nextRaw.forEach((want, i) => {
          checked += 1;
          if (raw.next() * 4294967296 !== want) fail(`nextRaw[${i}]`);
        });

        for (const [key, take] of Object.entries(SECTIONS)) {
          const rng = fresh();
          const want = s[key as keyof typeof SECTIONS] as (number | boolean)[];
          want.forEach((expected, i) => {
            checked += 1;
            const got = take(rng);
            const same = typeof expected === 'number' && typeof got === 'number'
              ? near(got, expected)
              : got === expected;
            if (!same) fail(`${key}[${i}]: got ${got}, expected ${expected}`);
          });
        }

        const shuf = fresh();
        s.shuffles.forEach((want, i) => {
          checked += 1;
          const got = shuf.shuffle([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);
          if (JSON.stringify(got) !== JSON.stringify(want)) fail(`shuffles[${i}]`);
        });

        const weigh = fresh();
        const items = s.weights.map((_, i) => i);
        s.weighted.forEach((want, i) => {
          checked += 1;
          if (weigh.weighted(items, (n) => s.weights[n]!) !== want) fail(`weighted[${i}]`);
        });

        for (const d of s.derived) {
          checked += 1;
          if (`${s.seed}::${d.label}` !== d.seed) fail(`derived seed for ${d.label}`);
          const dr = makeRng(d.seed);
          d.raw.forEach((want, i) => {
            if (dr.next() * 4294967296 !== want) fail(`derived ${d.label} raw[${i}]`);
          });
        }
        return checked;
      });
    }
  });

  it('seed phrases', () => {
    section('rng.seedPhrases', (fail) => {
      for (const c of golden.rng.seedPhrases) {
        if (makeSeedPhrase(c.entropy) !== c.phrase) fail(`makeSeedPhrase(${c.entropy})`);
      }
      return golden.rng.seedPhrases.length;
    });
  });

  it('pins the UTF-16 hazard, which no ASCII seed can catch', () => {
    // Measured, not warned about. `landnam` hashes the same whether you walk
    // UTF-8 bytes, UTF-16 code units or code points — and every seed this
    // game generates is ASCII, so no real seed can ever catch the bug. The
    // Norse strings in the golden file catch a UTF-8 port; only a surrogate
    // pair catches a code-point one.
    const norse = golden.rng.hashString.filter((c) => /[^\x20-\x7e]/.test(c.text));
    expect(norse.length, 'the golden file has no non-ASCII hash case left in it').toBeGreaterThan(0);
    expect('😀'.length, 'a surrogate pair is two UTF-16 code units').toBe(2);
  });
});
