// The parity contract with the Unreal build, owned by the repo that owns the
// source of truth.
//
// `landnam-ue` has had a C++ port of `src/hex` and `src/rng` since
// 2026-08-10, with an automation test (`LandnamParityTest.cpp`) that checks
// it against a big file of golden vectors. That arrangement had one hole,
// and it is the exact hole a parity harness exists to close: the vectors
// were generated by a script that lived on one machine and was never
// committed HERE. So this repo — which owns the code the vectors describe —
// had no idea the contract existed. Change `src/rng.ts`, and the vectors go
// stale, and the Unreal test keeps passing against yesterday's expectations
// while the two builds quietly disagree. A green parity test that cannot
// see one side of the parity is worse than none, because it is reassuring.
//
// `port/golden.json` is now that file, committed here. This test recomputes
// every vector in it from the live `src/hex` and `src/rng` and fails if any
// of them moved. The stored INPUTS are the spec and the stored OUTPUTS are
// the expectation, so the same file is both the thing Unreal asserts against
// and the thing this repo cannot drift from without being told.
//
// Workflow when a change here is deliberate: this test prints what moved,
// you regenerate (see port/rng.md), and you copy `port/golden.json` into the
// Unreal project at `Content/Data/golden.json`. Both sides move together or
// neither does.

import { describe, it, expect } from 'vitest';
import goldenText from '../port/golden.json?raw';
import {
  axialToOffset,
  column,
  directionTo,
  distance,
  findPath,
  fromPixel,
  line,
  neighbors,
  offsetToAxial,
  range,
  reachable,
  ring,
  round,
  toPixel,
  type Hex,
} from '../src/hex';
import { hashString, makeRng, makeSeedPhrase, stream, type Rng, type StreamName } from '../src/rng';

interface Golden {
  drawsPerStream: number;
  hexSize: number;
  hex: Record<string, Record<string, never>[]>;
  rng: {
    hashString: { text: string; hash: number }[];
    streams: {
      name: string;
      seed: string;
      nextRaw: number[];
      ints: number[];
      wideInts: number[];
      rolls: number[];
      chances: boolean[];
      floats: number[];
      shuffles: number[][];
      weights: number[];
      weighted: number[];
      derived: { label: string; seed: string; raw: number[] }[];
    }[];
    seedPhrases: { entropy: number; phrase: string }[];
  };
}

const golden = JSON.parse(goldenText) as Golden;
const SIZE = golden.hexSize;

/** Doubles cross JSON, so compare at a tolerance far tighter than any drift. */
const TOL = 1e-9;
const near = (a: number, b: number) => Math.abs(a - b) <= TOL;

const at = (q: number, r: number): Hex => ({ q, r });
const pairs = (hexes: Hex[]) => hexes.map((h) => [h.q, h.r]);

/**
 * The cost field the path vectors were measured over. Mirrors `GoldenCost` in
 * LandnamParityTest.cpp exactly, including the sign-safe modulo — `%` on a
 * negative differs between languages often enough that the C++ writes it out
 * the long way, and so does this.
 */
function goldenCost(h: Hex): number {
  if (distance(h, at(0, 0)) > 12) return Infinity;
  if ((h.q * 7 + h.r * 13) % 5 === 0) return Infinity;
  return 1 + ((((h.q * 3 + h.r * 5) % 4) + 4) % 4);
}

/** Collects every disagreement in a section rather than dying on the first. */
function section(name: string, run: (fail: (why: string) => void) => number): void {
  const failures: string[] = [];
  const checked = run((why) => failures.push(why));
  if (failures.length > 0 && (globalThis as { process?: { env: Record<string, string | undefined> } }).process?.env?.['LANDNAM_PARITY_VERBOSE']) {
    // eslint-disable-next-line no-console
    console.log(`PARITY ${name}:`, failures.slice(0, 12).join(' | '));
  }
  expect(checked, `${name}: no cases in the golden file`).toBeGreaterThan(0);
  expect(
    failures.slice(0, 6),
    `${name}: ${failures.length} of ${checked} vectors disagree with src/`,
  ).toEqual([]);
}

describe('the hex port contract', () => {
  it('round', () => {
    section('hex.round', (fail) => {
      const cases = golden.hex['round'] as unknown as { qf: number; rf: number; q: number; r: number }[];
      for (const c of cases) {
        const got = round(c.qf, c.rf);
        if (got.q !== c.q || got.r !== c.r) fail(`round(${c.qf},${c.rf})`);
      }
      return cases.length;
    });
  });

  it('toPixel and fromPixel', () => {
    section('hex.toPixel', (fail) => {
      const cases = golden.hex['toPixel'] as unknown as { q: number; r: number; x: number; y: number }[];
      for (const c of cases) {
        const got = toPixel(at(c.q, c.r), SIZE);
        if (!near(got.x, c.x) || !near(got.y, c.y)) fail(`toPixel(${c.q},${c.r})`);
      }
      return cases.length;
    });
    section('hex.fromPixel', (fail) => {
      const cases = golden.hex['fromPixel'] as unknown as { x: number; y: number; q: number; r: number }[];
      for (const c of cases) {
        const got = fromPixel(c.x, c.y, SIZE);
        if (got.q !== c.q || got.r !== c.r) fail(`fromPixel(${c.x},${c.y})`);
      }
      return cases.length;
    });
  });

  it('distance and line', () => {
    section('hex.distance', (fail) => {
      const cases = golden.hex['distance'] as unknown as
        { aq: number; ar: number; bq: number; br: number; d: number }[];
      for (const c of cases) {
        if (distance(at(c.aq, c.ar), at(c.bq, c.br)) !== c.d) fail(`distance(${c.aq},${c.ar}→${c.bq},${c.br})`);
      }
      return cases.length;
    });
    section('hex.line', (fail) => {
      const cases = golden.hex['line'] as unknown as
        { aq: number; ar: number; bq: number; br: number; hexes: number[][] }[];
      for (const c of cases) {
        const got = pairs(line(at(c.aq, c.ar), at(c.bq, c.br)));
        if (JSON.stringify(got) !== JSON.stringify(c.hexes)) fail(`line(${c.aq},${c.ar}→${c.bq},${c.br})`);
      }
      return cases.length;
    });
  });

  it('neighbors and directionTo', () => {
    section('hex.neighbors', (fail) => {
      const cases = golden.hex['neighbors'] as unknown as
        { q: number; r: number; neighbors: number[][]; directionTo: number[] }[];
      for (const c of cases) {
        const here = at(c.q, c.r);
        const got = neighbors(here);
        if (JSON.stringify(pairs(got)) !== JSON.stringify(c.neighbors)) fail(`neighbors(${c.q},${c.r})`);
        // The probe list, per the C++: the six neighbours, then a far hex,
        // then the hex itself — so both "not adjacent" answers are pinned.
        const probes = [...got, at(c.q + 2, c.r), here];
        c.directionTo.forEach((want, i) => {
          const probe = probes[i]!;
          if (directionTo(here, probe) !== want) fail(`directionTo(${c.q},${c.r} → ${probe.q},${probe.r})`);
        });
      }
      return cases.length;
    });
  });

  it('ring and range', () => {
    for (const which of ['ring', 'range'] as const) {
      section(`hex.${which}`, (fail) => {
        const cases = golden.hex[which] as unknown as
          { cq: number; cr: number; radius: number; hexes: number[][] }[];
        const fn = which === 'ring' ? ring : range;
        for (const c of cases) {
          const got = pairs(fn(at(c.cq, c.cr), c.radius));
          if (JSON.stringify(got) !== JSON.stringify(c.hexes)) fail(`${which}(${c.cq},${c.cr},${c.radius})`);
        }
        return cases.length;
      });
    }
  });

  it('offset conversions', () => {
    section('hex.offset', (fail) => {
      const cases = golden.hex['offset'] as unknown as
        { col: number; row: number; q: number; r: number; backCol: number; backRow: number; column: number }[];
      for (const c of cases) {
        const h = offsetToAxial(c.col, c.row);
        const back = axialToOffset(h);
        if (h.q !== c.q || h.r !== c.r) fail(`offsetToAxial(${c.col},${c.row})`);
        else if (back.col !== c.backCol || back.row !== c.backRow) fail(`axialToOffset(${c.col},${c.row})`);
        else if (column(h) !== c.column) fail(`column(${c.col},${c.row})`);
      }
      return cases.length;
    });
  });

  it('findPath', () => {
    section('hex.path', (fail) => {
      const cases = golden.hex['path'] as unknown as
        { sq: number; sr: number; gq: number; gr: number; reachable: boolean; cost: number; hexes: number[][] }[];
      for (const c of cases) {
        const got = findPath(at(c.sq, c.sr), at(c.gq, c.gr), goldenCost);
        const label = `findPath(${c.sq},${c.sr} → ${c.gq},${c.gr})`;
        // `Path` has no `reachable` flag — an unreachable goal comes back
        // with an empty route, which is what the golden file's boolean means.
        // Its cost is stored as -1 rather than Infinity, because JSON has no
        // way to write one; the C++ side skips the cost check for the same
        // reason (`if (!bWantReachable) continue;`), so this does too.
        const reached = got.hexes.length > 0;
        if (reached !== c.reachable) fail(`${label} reachable ${reached} vs ${c.reachable}`);
        else if (!reached) continue;
        else if (!near(got.cost, c.cost)) fail(`${label} cost ${got.cost} vs ${c.cost}`);
        else if (JSON.stringify(pairs(got.hexes)) !== JSON.stringify(c.hexes)) fail(`${label} route`);
      }
      return cases.length;
    });
  });

  it('reachable', () => {
    section('hex.reachable', (fail) => {
      const cases = golden.hex['reachable'] as unknown as
        { sq: number; sr: number; budget: number; entries: { q: number; r: number; cost: number }[] }[];
      for (const c of cases) {
        const got = reachable(at(c.sq, c.sr), c.budget, goldenCost);
        const label = `reachable(${c.sq},${c.sr},${c.budget})`;
        if (got.size !== c.entries.length) fail(`${label} size ${got.size} vs ${c.entries.length}`);
        else {
          for (const e of c.entries) {
            const cost = got.get(`${e.q},${e.r}`);
            if (cost === undefined || !near(cost, e.cost)) fail(`${label} at ${e.q},${e.r}`);
          }
        }
      }
      return cases.length;
    });
  });
});

// --- The generator ---

/**
 * Every section draws from its OWN fresh generator on the stream's seed, and
 * then sequentially within itself. Recovered by solving against the committed
 * vectors rather than assumed — `wideInts` is `int(-50, 250)`, `floats` is
 * `float(-2.5, 7.5)` and `chances` is `chance(0.3)`, none of which the C++
 * could have told me, since the generating script was never in this repo.
 * (Solved, not guessed: the six streams together pin the chance probability
 * to (0.297557, 0.302485], and 0.3 is the only round number in it.)
 */
const SECTIONS = {
  ints: (r: Rng) => r.int(1, 6),
  wideInts: (r: Rng) => r.int(-50, 250),
  rolls: (r: Rng) => r.roll(2, 6),
  chances: (r: Rng) => r.chance(0.3),
  floats: (r: Rng) => r.float(-2.5, 7.5),
} as const;

describe('the rng port contract', () => {
  it('hashString', () => {
    section('rng.hashString', (fail) => {
      for (const c of golden.rng.hashString) {
        if (hashString(c.text) !== c.hash) fail(`hashString(${JSON.stringify(c.text)})`);
      }
      return golden.rng.hashString.length;
    });
  });

  it('every stream, draw for draw', () => {
    for (const s of golden.rng.streams) {
      section(`rng.${s.name}`, (fail) => {
        let checked = 0;
        // The stream seed itself is part of the contract: rename a stream and
        // every existing seed builds a different world.
        const seed = 'raven-skerry-317';
        if (`${seed}#${s.name}` !== s.seed) fail(`stream seed for ${s.name} is ${s.seed}`);

        const fresh = () => stream(seed, s.name as StreamName);

        const raw = fresh();
        s.nextRaw.forEach((want, i) => {
          checked += 1;
          if (raw.next() * 4294967296 !== want) fail(`nextRaw[${i}]`);
        });

        for (const [key, take] of Object.entries(SECTIONS)) {
          const rng = fresh();
          const want = s[key as keyof typeof SECTIONS] as (number | boolean)[];
          want.forEach((expected, i) => {
            checked += 1;
            const got = take(rng);
            const same = typeof expected === 'number' && typeof got === 'number'
              ? near(got, expected)
              : got === expected;
            if (!same) fail(`${key}[${i}]: got ${got}, expected ${expected}`);
          });
        }

        const shuf = fresh();
        s.shuffles.forEach((want, i) => {
          checked += 1;
          const got = shuf.shuffle([0, 1, 2, 3, 4, 5, 6, 7, 8, 9]);
          if (JSON.stringify(got) !== JSON.stringify(want)) fail(`shuffles[${i}]`);
        });

        const weigh = fresh();
        const items = s.weights.map((_, i) => i);
        s.weighted.forEach((want, i) => {
          checked += 1;
          if (weigh.weighted(items, (n) => s.weights[n]!) !== want) fail(`weighted[${i}]`);
        });

        for (const d of s.derived) {
          checked += 1;
          if (`${s.seed}::${d.label}` !== d.seed) fail(`derived seed for ${d.label}`);
          const dr = makeRng(d.seed);
          d.raw.forEach((want, i) => {
            if (dr.next() * 4294967296 !== want) fail(`derived ${d.label} raw[${i}]`);
          });
        }
        return checked;
      });
    }
  });

  it('seed phrases', () => {
    section('rng.seedPhrases', (fail) => {
      for (const c of golden.rng.seedPhrases) {
        if (makeSeedPhrase(c.entropy) !== c.phrase) fail(`makeSeedPhrase(${c.entropy})`);
      }
      return golden.rng.seedPhrases.length;
    });
  });

  it('pins the UTF-16 hazard, which no ASCII seed can catch', () => {
    // Measured, not warned about. `landnam` hashes the same whether you walk
    // UTF-8 bytes, UTF-16 code units or code points — and every seed this
    // game generates is ASCII, so no real seed can ever catch the bug. The
    // Norse strings in the golden file catch a UTF-8 port; only a surrogate
    // pair catches a code-point one.
    const norse = golden.rng.hashString.filter((c) => /[^\x20-\x7e]/.test(c.text));
    expect(norse.length, 'the golden file has no non-ASCII hash case left in it').toBeGreaterThan(0);
    expect('😀'.length, 'a surrogate pair is two UTF-16 code units').toBe(2);
  });
});
