// Exports the game's content tables to Unreal DataTable JSON.
//
//   node ue-port/tools/export-data.mjs
//
// Reads the real src/data modules, so the tables can never drift from the game.
// Import each file in Unreal with the matching row struct from LandnamDataRows.h
// (see ue-port/README.md). Adding content in the TS and re-running this is the whole
// workflow — no engine code is touched, exactly as the project's data-driven rule says.

import { mkdirSync, writeFileSync } from 'node:fs';
import { resolve } from 'node:path';
import { loadGame, repoRoot } from './load-game.mjs';

const outDir = resolve(repoRoot, 'ue-port/Content/Data');

const { Terrain, Foes } = await loadGame({
  Terrain: './src/data/terrain.ts',
  Foes: './src/data/foes.ts',
});

/** Unreal's DataTable JSON has no Infinity; -1 is the impassable sentinel, matching
 *  the FHexCostDelegate convention in LandnamHex.h. */
const finiteCost = (cost) => (Number.isFinite(cost) ? cost : -1);

function write(name, rows) {
  const file = resolve(outDir, name);
  writeFileSync(file, `${JSON.stringify(rows, null, 1)}\n`);
  console.log(`wrote ${file} (${rows.length} rows)`);
}

// ---- terrain ----

// The Terrain union in src/state/types.ts, in map order. Kept explicit so a new
// terrain fails loudly here rather than silently exporting a short table.
const TERRAIN_IDS = ['ocean', 'shore', 'meadow', 'forest', 'hills', 'mountains', 'bog', 'valley'];

const terrainRows = TERRAIN_IDS.map((id) => {
  const def = Terrain.terrainDef(id);
  if (def === undefined) throw new Error(`terrainDef('${id}') returned nothing — did the id list drift?`);
  return {
    Name: def.id, // DataTable row name
    Id: def.id,
    DisplayName: def.name,
    Cost: finiteCost(def.cost),
    Forage: def.forage,
    Hunt: def.hunt,
    Fish: def.fish,
    Wood: def.wood,
    bBlocksSight: def.blocksSight,
    bIsLand: Terrain.isLand(def.id),
    Fill: def.fill,
    Edge: def.edge,
  };
});

const missingLand = Terrain.LAND_TERRAINS.filter((id) => !TERRAIN_IDS.includes(id));
if (missingLand.length > 0) throw new Error(`LAND_TERRAINS has ids this export does not know: ${missingLand}`);

write('terrain.json', terrainRows);

// ---- foes ----

const foeRows = Foes.FOE_ARCHETYPES.map((foe) => ({
  Name: foe.id,
  Id: foe.id,
  Kind: foe.kind,
  Budget: foe.budget,
  // Repeats are meaningful: they are how the spread leans, so keep them.
  Favours: [...foe.favours],
  Toughness: foe.toughness,
  Temperament: foe.temperament,
  Throws: foe.throws,
  Weight: foe.weight,
}));

write('foes.json', foeRows);

// ---- foe naming ----

// Not a DataTable — three word lists the name generator draws from. Load it with
// FJsonSerializer, or paste the arrays into a UDataAsset if you prefer editor tuning.
const names = {
  note: 'Generated by ue-port/tools/export-data.mjs from src/data/foes.ts. Not a DataTable.',
  FoeNames: [...Foes.FOE_NAMES],
  FoeBynames: [...Foes.FOE_BYNAMES],
  ChampionBynames: [...Foes.CHAMPION_BYNAMES],
};

mkdirSync(outDir, { recursive: true });
writeFileSync(resolve(outDir, 'foe-names.json'), `${JSON.stringify(names, null, 1)}\n`);
console.log(`wrote ${resolve(outDir, 'foe-names.json')} (${names.FoeNames.length} names, ` +
  `${names.FoeBynames.length} bynames, ${names.ChampionBynames.length} champion bynames)`);
