// GENERATED by scripts/battle-tables.ts — do not edit.
//
//   npm run battle-tables
//
// The foes, the ground, the authored fields and the lore, out of src/data.
// Content is authored in ONE place and this is a copy of it, which is the
// project's oldest architectural rule carried across the port.
//
// Order is load-bearing twice over: `FOE_ARCHETYPES` is walked by
// `rng.weighted` in declaration order, and the two field tables are picked
// out of by index. Both are emitted exactly as declared.

#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace Landnam
{
namespace Tables
{
	// ---- The men who come (src/data/foes.ts) ----

	struct FFoeArchetype
	{
		std::string Id;
		std::string Kind;
		/** Points spread over the four stats, on top of a base of 1 each. */
		int32_t Budget;
		/**
		 * Leans the spread toward these. Favoured stats appear MORE THAN ONCE
		 * and the pool is these followed by all four in stat order, so a
		 * favourite is drawn more often — the duplication IS the weighting.
		 */
		std::vector<std::string> Favours;
		int32_t Toughness;
		std::string Temperament;
		int32_t Throws;
		int32_t Weight;
	};

	const std::vector<FFoeArchetype> FoeArchetypes = {
		{ "scout", "Scout", 6, { "wits", "wits", "spirit" }, -2, "cautious", 2, 10 },
		{ "raider", "Raider", 8, { "might", "might", "spirit" }, 0, "aggressive", 1, 12 },
		{ "skirmisher", "Skirmisher", 8, { "wits", "might", "spirit" }, -1, "flanker", 1, 9 },
		{ "huscarl", "Huscarl", 11, { "might", "spirit", "craft" }, 3, "aggressive", 0, 5 },
	};

	inline const FFoeArchetype* ArchetypeById(const std::string& Id)
	{
		for (const FFoeArchetype& Row : FoeArchetypes) if (Row.Id == Id) return &Row;
		return nullptr;
	}

	const std::vector<std::string> FoeNames = { "Hrafn", "Ketil", "Bui", "Starkad", "Vagn", "Glum", "Hallvard", "Solvi", "Refr", "Thrand", "Eyjolf", "Kalf", "Hogni", "Vestein", "Bard", "Ozur" };
	const std::vector<std::string> FoeBynames = { "the Hungry", "Blackteeth", "the Landless", "Crookback", "the Loud", "Ill-Luck", "the Thin", "Wolf-Jaw", "the Stranger", "Cold-Iron" };
	const std::vector<std::string> ChampionBynames = { "Skull-Splitter", "the Bloody", "Hard-Counsel", "Ship-Burner", "the Old Wolf", "Battle-Glad", "Iron-Beard", "the Unforgiven" };

	// ---- The ground a fight is rolled on (src/sim/battlefield.ts) ----

	struct FGroundMix
	{
		std::string Terrain;
		double Rough, Block, Water;
	};

	/**
	 * Read in this order and no other: block, then water, then rough, each
	 * against the running sum. One `next()` per hex decides all three.
	 */
	const std::vector<FGroundMix> GroundMixes = {
		{ "ocean", 0.06, 0.14, 0.24 },
		{ "shore", 0.12, 0.03, 0.1 },
		{ "meadow", 0.08, 0.02, 0 },
		{ "forest", 0.2, 0.16, 0 },
		{ "hills", 0.26, 0.1, 0 },
		{ "mountains", 0.3, 0.22, 0 },
		{ "bog", 0.42, 0.04, 0.12 },
		{ "valley", 0.1, 0.03, 0.04 },
	};

	inline const FGroundMix& MixFor(const std::string& Terrain)
	{
		for (const FGroundMix& Row : GroundMixes) if (Row.Terrain == Terrain) return Row;
		// `MIXES[terrain] ?? MIXES.meadow` — the fallback is meadow, index 2.
		return GroundMixes[2];
	}

	/** What the log calls the ground. Same switch as `groundName`. */
	inline std::string GroundName(const std::string& Terrain)
	{
		if (Terrain == "bog") return "the sucking peat";
		if (Terrain == "forest") return "close trees";
		if (Terrain == "hills") return "broken slope";
		if (Terrain == "mountains") return "bare rock";
		if (Terrain == "shore") return "wet sand";
		if (Terrain == "ocean") return "lashed hulls";
		if (Terrain == "valley") return "good grass";
		return "open ground";
	}

	// ---- The authored fields (src/data/seaFields.ts, src/data/raidFields.ts) ----

	struct FSeaField
	{
		std::string Id;
		std::string Line;
		std::vector<std::string> Rows;
	};

	const std::vector<FSeaField> SeaFields = {
		{ "lashed-hulls", "The hulls came together and the lashings went over the rails: one deck now, and no ground to give.", { "~.....~", "~..#..~", "~.,...~", "~,,.,,~", "~.....~", "~..,..~", "~.#...~", "~.....~", "~.....~" } },
		{ "the-boarding", "Their bow rode up over ours and locked there, and the only way this ends is across it.", { "~.....~", "~..#..~", "~~....~", "~~~,~~~", "~~,.~~~", "~.....~", "~.#...~", "~.....~", "~.....~" } },
		{ "the-shallows", "Both keels took the sand at once, and it was fought out in the shallows, knee-deep among the skerries.", { ".......", "...,...", "~,.#.,~", ".,~.~,.", "..,.,..", "~.#.,.~", ".,...,.", ".......", "......." } },
	};

	struct FRaidField
	{
		std::string Id;
		std::string Line;
		/** A plot the steading must hold for this approach to be possible. */
		std::string Needs;
		std::vector<std::string> Rows;
	};

	const std::vector<FRaidField> RaidFields = {
		{ "open-approach", "They came straight up the in-field, the way we walk it ourselves.", "", { ".......", ".......", "..,.#..", ".,..,..", "#..,...", "==G====", ".......", ".......", "..,H..." } },
		{ "the-strand-gate", "They beached below us and came along the strand, between the wall and the water.", "water", { ".......", ".......", "~~,....", "~,.....", "~~..,..", "~=G====", "~......", ".......", "...H,.." } },
		{ "the-wood-shoulder", "They came out of our own trees, where the wood shoulders the wall.", "wood", { ".......", ".......", "...,##.", "....,##", ".,...#.", "===G==#", "......,", ".......", "..H...." } },
		{ "the-hollow-way", "They came up the hollow way, single file between the banks, because it is the only way there is.", "", { ".......", ".......", ".#,#...", ".#,#,..", ".#,#...", "==G====", ".......", ".......", "...H..." } },
		{ "the-ford", "They took the stream at both fords, wet to the knee before a blow was struck.", "water", { ".......", ".......", ".......", "~~,~~,~", ".......", "==G====", ".......", ".......", "..H...." } },
		{ "the-burnt-fields", "They came through the stubble with the ricks for cover, burning nothing yet.", "", { ".......", ".......", ",,..,,.", "..#,...", ",..,.#,", "====G==", ".......", "..,....", "....H.." } },
	};

	// ---- What the band has worked out (src/data/lore.ts) ----

	struct FLoreRow
	{
		std::string Id;
		double Check, Solace, Sea, Bite, Warmth, Mend, Physic, Wall;
	};

	const std::vector<FLoreRow> Lore = {
		{ "runes", 1, 0.4, 0, 0, 0, 0, 0, 0 },
		{ "shipwright", 0, 0, 1, 0, 0, 0, 0, 0 },
		{ "smithing", 0, 0, 0, 1, 0, 0, 0, 0 },
		{ "skywatch", 0, 0, 0, 0, 1, 0, 0, 0 },
		{ "leechcraft", 0, 0, 0, 0, 0, 1, 2, 0 },
		{ "shieldcraft", 0, 0, 0, 0, 0, 0, 0, 1 },
	};

	// ---- What a bad hour leaves behind (src/data/injuries.ts) ----

	struct FInjuryTemplate
	{
		std::string Label;
		int32_t Heals;
		/**
		 * A stat the wound drags, and whether it drags it at all. The absent
		 * ones are DROPPED from the canonical form, never written as nought,
		 * so "has it" and "how much" are two fields. Declared in the order the
		 * canonical form sorts them: craft, might, spirit, wits.
		 */
		bool bCraft; int32_t Craft;
		bool bMight; int32_t Might;
		bool bSpirit; int32_t Spirit;
		bool bWits; int32_t Wits;
	};

	const std::vector<FInjuryTemplate> Injuries = {
		{ "Shield-arm broken", 24, false, 0, true, -2, false, 0, false, 0 },
		{ "Gash across the brow", 12, false, 0, false, 0, false, 0, true, -1 },
		{ "Ribs stove in", 18, false, 0, true, -1, true, -1, false, 0 },
		{ "Hamstrung", 20, false, 0, true, -1, false, 0, true, -1 },
		{ "Hand half-crushed", 16, true, -2, false, 0, false, 0, false, 0 },
		{ "Something gone behind the eyes", 26, false, 0, false, 0, true, -2, false, 0 },
		{ "Wound that will not close", 22, true, -1, true, -1, false, 0, false, 0 },
	};

	/** Some wounds never mend. Rolled rarely; `heals` is absurdly high. */
	const std::vector<FInjuryTemplate> LastingInjuries = {
		{ "Lost an eye", 9999, false, 0, false, 0, false, 0, true, -2 },
		{ "Walks with a stick now", 9999, false, 0, true, -1, true, -1, false, 0 },
	};

	/** How a fighter died, for the saga — and for the hashed `fate`. */
	const std::vector<std::string> Deaths = { "cut down in the press", "took a spear and did not get up", "bled out before the fight was over", "went under and was not seen again", "died of the wound that night" };

	// ---- The numbers ----

	constexpr int32_t FieldWidth = 7;
	constexpr int32_t FieldHeight = 9;
	constexpr int32_t FrontWidth = 4;
	constexpr int32_t WallRow = 5;
	constexpr int32_t MiddleRowFirst = 2;
	constexpr int32_t MiddleRowCount = 5;

	constexpr int32_t BaseMoves = 3;
	constexpr int32_t MaxFoes = 6;
	constexpr int32_t MaxRaiders = 9;
	constexpr int32_t MaxRaidersFamed = 14;
	constexpr double RaidPerPoint = 0.5;
	constexpr int32_t JarlWord = 3;

	constexpr int32_t ChampionMight = 1;
	constexpr int32_t ChampionSpirit = 1;
	constexpr int32_t ChampionToughness = 4;
	constexpr int32_t ScarMax = 4;
	constexpr int32_t ScarToughness = 2;

	constexpr double NerveHit = 10;
	constexpr double NerveAllyDown = 20;
	constexpr double NerveWallShattered = 10;
	constexpr double NerveOutnumbered = 12;
	constexpr double NerveKill = 12;
	constexpr double NerveLeaderFell = 25;
	constexpr double NerveKinFell = 15;
	constexpr double RallyNerve = 35;
	constexpr int32_t RallyDc = 10;
	constexpr double SteadiedPerLink = 0.25;

	constexpr int32_t ThrowRange = 3;
	constexpr int32_t DefendBonus = 3;
	constexpr int32_t WallExposed = 3;
	constexpr int32_t OutnumberedPenalty = 2;
	constexpr int32_t MaxOutnumbered = 2;
	constexpr int32_t WallPushMax = 2;
	constexpr int32_t ReachRange = 2;
	constexpr int32_t ReachPenalty = 1;
	constexpr int32_t ReachDamageOff = 1;
	constexpr int32_t WarcryRange = 2;
	constexpr double WarcryHeart = 6;
	constexpr double WarcryDread = 4;

	constexpr int32_t WallBonusOne = 2;
	constexpr int32_t WallBonusFull = 3;
	constexpr int32_t ShieldInWall = 1;
	constexpr int32_t DisengageCost = 2;
	constexpr int32_t PatienceRounds = 12;
	constexpr int32_t RoundLimit = 50;

	constexpr int32_t XpPerAdvance = 12;
	constexpr int32_t XpPerKill = 4;
	constexpr int32_t XpSurvived = 2;
	constexpr int32_t XpWon = 2;
	constexpr int32_t LootFoodPerFoe = 2;
	constexpr int32_t LootWoodPerFoe = 1;
	constexpr double KinGrief = 30;
	constexpr int32_t GriefDays = 3;

	/**
	 * What holding, breaking off, or being overrun is worth to the roll that
	 * decides whether somebody dragged off the field lives.
	 */
	constexpr int32_t FateHeld = 2;
	constexpr int32_t FateWithdrew = 1;
	constexpr int32_t FateOverrun = -1;

	// ---- What somebody coming for the steading is worth (src/sim/raid.ts) ----

	/** What share of the store a successful sack carries off. */
	constexpr double SackShare = 0.4;
	/** The most hands a single sacking carries off. Hands, never sworn. */
	constexpr int32_t SackTakes = 2;
	/** Visible wealth: a coast can count roofs from a ridge. */
	constexpr double WorthPerRoof = 0.4;
	/** What a point of defensibility takes back off it. */
	constexpr double DefencePer = 0.5;
	/** And a point of watch kept. A watch not kept decays. */
	constexpr double WatchPer = 0.2;
}
}
