// GENERATED by scripts/party-tables.ts from src/data — do not hand-edit.
// Add a name or a trait in src/data/*.ts and re-run `npm run party-tables`.
//
// Order matters and is load-bearing: every list here is drawn from with
// `rng.pick(index)`, so reordering one silently changes every warband ever
// rolled from every seed. That is why this is generated rather than retyped.

#pragma once

#include <cstdint>
#include <map>
#include <string>
#include <utility>
#include <vector>

namespace Landnam
{
namespace Tables
{
	const std::vector<std::string> Men = {
		"Arnkel",
		"Bersi",
		"Bjarni",
		"Egil",
		"Eyvind",
		"Finnbogi",
		"Gizur",
		"Grim",
		"Gunnar",
		"Halli",
		"Hoskuld",
		"Ingimund",
		"Ketil",
		"Kjartan",
		"Leif",
		"Njal",
		"Odd",
		"Orm",
		"Ragnar",
		"Skarphedin",
		"Snorri",
		"Steinar",
		"Sveinn",
		"Thorbjorn",
		"Thorgeir",
		"Thorkel",
		"Thorstein",
		"Toki",
		"Ulf",
		"Vali",
		"Vemund",
		"Ozur",
	};

	const std::vector<std::string> Women = {
		"Aud",
		"Asdis",
		"Bergthora",
		"Freydis",
		"Groa",
		"Gudrid",
		"Gudrun",
		"Halldora",
		"Hallgerd",
		"Helga",
		"Hervor",
		"Ingibjorg",
		"Jorunn",
		"Ragnheid",
		"Sigrid",
		"Steinunn",
		"Thorbjorg",
		"Thordis",
		"Thorgerd",
		"Thurid",
		"Unn",
		"Yngvild",
	};

	const std::vector<std::string> Bynames = {
		"the Quiet",
		"the Bold",
		"Ironhand",
		"the Lucky",
		"Longshanks",
		"the Grim",
		"Half-Troll",
		"the Fair",
		"Crow-Eye",
		"the Old",
		"Seal-Bane",
		"the Red",
		"Wave-Tamer",
		"the Unwashed",
		"Two-Axe",
		"the Wise",
		"Salt-Beard",
		"the Slight",
		"Bear-Shirt",
		"the Silent",
		"Cold-Hands",
		"Sheep-Thief",
		"the Steady",
		"Oak-Knee",
	};

	const std::vector<std::string> LandingNames = {
		"Kelpstrand",
		"Grey Skerry",
		"Driftwood Bay",
		"Rimefjord",
		"Gullsand",
		"Whalebone Shore",
		"Cold Landing",
		"The Long Beach",
		"Ravenmouth",
		"Stonewash",
	};

	/** A trait's stat nudge, applied once at generation. */
	struct FTraitRow { std::string Id; int Might, Wits, Spirit, Craft; };
	const std::vector<FTraitRow> Traits = {
		{ "hunter", 0, 1, 0, 0 },
		{ "shipwright", 0, 0, 0, 1 },
		{ "berserk", 1, 0, -1, 0 },
		{ "hardy", 0, 0, 1, 0 },
		{ "healer", 0, 0, 0, 1 },
		{ "seafarer", 0, 1, 0, 0 },
		{ "quarrelsome", 1, -1, 0, 0 },
		{ "steadfast", 0, 0, 1, 0 },
		{ "sharpeyed", 0, 1, 0, 0 },
		{ "ox", 1, 0, 0, 0 },
	};

	const std::map<std::string, std::pair<std::string, std::string>> ElderTies = {
		{ "mm", { "father", "son" } },
		{ "ff", { "mother", "daughter" } },
		{ "mf", { "father", "daughter" } },
		{ "fm", { "mother", "son" } },
	};

	const std::map<std::string, std::vector<std::pair<std::string, std::string>>> PeerTies = {
		{ "mm", { { "brother", "brother" }, { "oath-brother", "oath-brother" }, { "cousin", "cousin" } } },
		{ "ff", { { "sister", "sister" }, { "cousin", "cousin" } } },
		{ "mf", { { "brother", "sister" }, { "husband", "wife" }, { "cousin", "cousin" } } },
	};

	const std::vector<std::string> ClanNames = {
		"Grimsgarth",
		"Ketilstead",
		"Hrafnsvik",
		"Bergthorsholt",
		"Ulfsfell",
		"Skallagrimsstead",
		"Thorgestholt",
		"Vigahall",
		"Eyrarbakki",
		"Svartafell",
	};

	const std::vector<std::string> NativeNames = {
		"The Reed Camp",
		"Sealwatch",
		"The Long Weir",
		"Threefires",
		"Otter Landing",
		"The Standing Stones",
		"Birchwater",
		"The Winter Camp",
		"Nine Nets",
		"Elkford",
	};

	constexpr int32_t ClanCount = 4;
	constexpr int32_t ClanMinGap = 6;
	constexpr int32_t ClanMaxGap = 13;
	constexpr int32_t ClanOpening = -10;
	constexpr int32_t NativeOpening = 10;
	const std::string ClanNoun = "steading";
	const std::string NativeNoun = "camp";

	/** Which terrains stop a view. Only mountains stop one from high ground. */
	const std::map<std::string, bool> BlocksSight = {
		{ "ocean", false },
		{ "shore", false },
		{ "meadow", false },
		{ "forest", true },
		{ "hills", true },
		{ "mountains", true },
		{ "bog", false },
		{ "valley", false },
	};

	/** Fixed places, IN SEEDING ORDER — seedPlaces walks this list. */
	struct FPlaceKindRow { std::string Id; std::vector<std::string> Ground; int32_t MinFromLanding; };
	const std::vector<FPlaceKindRow> PlaceKinds = {
		{ "monastery", { "shore" }, 6 },
		{ "town", { "shore", "valley", "meadow" }, 11 },
		{ "wreck", { "shore" }, 3 },
		{ "oreseam", { "bog", "hills", "mountains" }, 4 },
	};
	constexpr int32_t PlaceMaxFromLanding = 16;

	/** How far the band sees on day one. The calendar itself is a later stage. */
	constexpr int32_t SightOnDayOne = 3;
	constexpr int32_t SaveVersion = 31;
}
}
