// GENERATED by scripts/party-tables.ts from src/data — do not hand-edit.
// Add a name or a trait in src/data/*.ts and re-run `npm run party-tables`.
//
// Order matters and is load-bearing: every list here is drawn from with
// `rng.pick(index)`, so reordering one silently changes every warband ever
// rolled from every seed. That is why this is generated rather than retyped.

#pragma once

#include <cstdint>
#include <limits>
#include <map>
#include <string>
#include <utility>
#include <vector>

namespace Landnam
{
namespace Tables
{
	const std::vector<std::string> Men = {
		"Arnkel",
		"Bersi",
		"Bjarni",
		"Egil",
		"Eyvind",
		"Finnbogi",
		"Gizur",
		"Grim",
		"Gunnar",
		"Halli",
		"Hoskuld",
		"Ingimund",
		"Ketil",
		"Kjartan",
		"Leif",
		"Njal",
		"Odd",
		"Orm",
		"Ragnar",
		"Skarphedin",
		"Snorri",
		"Steinar",
		"Sveinn",
		"Thorbjorn",
		"Thorgeir",
		"Thorkel",
		"Thorstein",
		"Toki",
		"Ulf",
		"Vali",
		"Vemund",
		"Ozur",
	};

	const std::vector<std::string> Women = {
		"Aud",
		"Asdis",
		"Bergthora",
		"Freydis",
		"Groa",
		"Gudrid",
		"Gudrun",
		"Halldora",
		"Hallgerd",
		"Helga",
		"Hervor",
		"Ingibjorg",
		"Jorunn",
		"Ragnheid",
		"Sigrid",
		"Steinunn",
		"Thorbjorg",
		"Thordis",
		"Thorgerd",
		"Thurid",
		"Unn",
		"Yngvild",
	};

	const std::vector<std::string> Bynames = {
		"the Quiet",
		"the Bold",
		"Ironhand",
		"the Lucky",
		"Longshanks",
		"the Grim",
		"Half-Troll",
		"the Fair",
		"Crow-Eye",
		"the Old",
		"Seal-Bane",
		"the Red",
		"Wave-Tamer",
		"the Unwashed",
		"Two-Axe",
		"the Wise",
		"Salt-Beard",
		"the Slight",
		"Bear-Shirt",
		"the Silent",
		"Cold-Hands",
		"Sheep-Thief",
		"the Steady",
		"Oak-Knee",
	};

	const std::vector<std::string> LandingNames = {
		"Kelpstrand",
		"Grey Skerry",
		"Driftwood Bay",
		"Rimefjord",
		"Gullsand",
		"Whalebone Shore",
		"Cold Landing",
		"The Long Beach",
		"Ravenmouth",
		"Stonewash",
	};

	/**
	 * A trait: a stat nudge applied once at generation, how hard the mood
	 * swings, and the tags two people grate over.
	 *
	 * `Temper` scales the daily mood drift, so a steadfast man moves half as
	 * far toward the day's target as an ordinary one. `Tags` and `Frictions`
	 * are what `friction()` counts across a pair — a Quarrelsome beside a
	 * Berserk is bad blood waiting for a bad day.
	 */
	struct FTraitRow
	{
		std::string Id;
		int Might, Wits, Spirit, Craft;
		double Temper;
		std::vector<std::string> Tags, Frictions;
	};
	const std::vector<FTraitRow> Traits = {
		{ "hunter", 0, 1, 0, 0, 1, { "forager", "hunter" }, {  } },
		{ "shipwright", 0, 0, 0, 1, 1, { "builder" }, {  } },
		{ "berserk", 1, 0, -1, 0, 1.6, { "fighter", "volatile" }, { "volatile", "anchor" } },
		{ "hardy", 0, 0, 1, 0, 0.6, { "hardy" }, {  } },
		{ "healer", 0, 0, 0, 1, 1, { "healer" }, {  } },
		{ "seafarer", 0, 1, 0, 0, 1, { "sailor", "fisher" }, {  } },
		{ "quarrelsome", 1, -1, 0, 0, 1.8, { "volatile" }, { "volatile", "hardy", "anchor", "healer" } },
		{ "steadfast", 0, 0, 1, 0, 0.5, { "hardy", "anchor" }, {  } },
		{ "sharpeyed", 0, 1, 0, 0, 1, { "scout" }, {  } },
		{ "ox", 1, 0, 0, 0, 1, { "fighter", "labourer" }, {  } },
	};

	const std::map<std::string, std::pair<std::string, std::string>> ElderTies = {
		{ "mm", { "father", "son" } },
		{ "ff", { "mother", "daughter" } },
		{ "mf", { "father", "daughter" } },
		{ "fm", { "mother", "son" } },
	};

	const std::map<std::string, std::vector<std::pair<std::string, std::string>>> PeerTies = {
		{ "mm", { { "brother", "brother" }, { "oath-brother", "oath-brother" }, { "cousin", "cousin" } } },
		{ "ff", { { "sister", "sister" }, { "cousin", "cousin" } } },
		{ "mf", { { "brother", "sister" }, { "husband", "wife" }, { "cousin", "cousin" } } },
	};

	const std::vector<std::string> ClanNames = {
		"Grimsgarth",
		"Ketilstead",
		"Hrafnsvik",
		"Bergthorsholt",
		"Ulfsfell",
		"Skallagrimsstead",
		"Thorgestholt",
		"Vigahall",
		"Eyrarbakki",
		"Svartafell",
	};

	const std::vector<std::string> NativeNames = {
		"The Reed Camp",
		"Sealwatch",
		"The Long Weir",
		"Threefires",
		"Otter Landing",
		"The Standing Stones",
		"Birchwater",
		"The Winter Camp",
		"Nine Nets",
		"Elkford",
	};

	constexpr int32_t ClanCount = 4;
	constexpr int32_t ClanMinGap = 6;
	constexpr int32_t ClanMaxGap = 13;
	constexpr int32_t ClanOpening = -10;
	/** How hard each kind hits when it comes. */
	constexpr double ClanStrength = 1.15;
	constexpr double NativeStrength = 0.9;
	constexpr int32_t NativeOpening = 10;
	const std::string ClanNoun = "steading";
	const std::string NativeNoun = "camp";

	/**
	 * Terrain, as the sim reads it: what it costs to enter, the firewood a
	 * camp night on it yields, and whether it stops a view. `Cost` is infinite
	 * for open sea — impassable on foot, and the knarr's own rules live in the
	 * travel code rather than here. `Wood` is also what the timber measure of
	 * a site is summed from, over the hex and its ring. `Forage`, `Hunt` and
	 * `Fish` are the base yields a day's gathering starts from.
	 */
	struct FTerrainRow
	{
		std::string Id;
		double Cost;
		int32_t Wood, Forage, Hunt, Fish;
		bool bBlocksSight;
	};
	const std::vector<FTerrainRow> Terrains = {
		{ "ocean", std::numeric_limits<double>::infinity(), 0, 0, 0, 5, false },
		{ "shore", 1, 1, 2, 1, 4, false },
		{ "meadow", 1, 1, 3, 2, 0, false },
		{ "forest", 2, 4, 4, 4, 0, true },
		{ "hills", 2, 2, 2, 3, 0, true },
		{ "mountains", 4, 0, 1, 1, 0, true },
		{ "bog", 3, 1, 2, 2, 1, false },
		{ "valley", 1, 2, 5, 3, 0, false },
	};
	inline const FTerrainRow* TerrainById(const std::string& Id)
	{
		for (const FTerrainRow& Row : Terrains) if (Row.Id == Id) return &Row;
		return nullptr;
	}
	inline bool BlocksSight(const std::string& Id)
	{
		const FTerrainRow* Row = TerrainById(Id);
		return Row && Row->bBlocksSight;
	}

	/**
	 * The year, IN ORDER OF PLAY — day 1 is high summer. The index into this
	 * list is `floor((day-1) / SeasonLength) % 4`, so reordering it moves
	 * every season of every run.
	 */
	struct FSeasonRow
	{
		std::string Id;
		double Forage;
		int32_t TravelPenalty, Sight, Firewood;
	};
	const std::vector<FSeasonRow> Seasons = {
		{ "summer", 1.35, 0, 3, 1 },
		{ "autumn", 1, 0, 2, 2 },
		{ "winter", 0.15, 1, 1, 6 },
		{ "spring", 0.7, 0, 2, 2 },
	};
	constexpr int32_t SeasonLength = 24;
	constexpr int32_t YearLength = 96;
	constexpr int32_t WinterDeepening = 2;
	constexpr int32_t WinterDepthMax = 6;
	constexpr int32_t WinterBiteMax = 4;

	/**
	 * The weather, IN DECLARATION ORDER — weighted() subtracts in this order.
	 *
	 * Weights are per season and an absent season means never, so the pool is
	 * filtered to the ones with a weight above nought before the pick, keeping
	 * this order. Reorder the rows and every seed gets a different sky.
	 */
	struct FWeatherRow
	{
		std::string Id, Label;
		int32_t Travel;
		bool bShutsTheSea;
		int32_t Firewood, Sight;
		/** Per season, in SeasonOrder. Nought means it never happens then. */
		std::vector<double> Weight;
	};
	const std::vector<FWeatherRow> Weathers = {
		{ "fair", "Fair", 0, false, 0, 0, { 30, 22, 20, 24 } },
		{ "gale", "A gale", 0, true, 1, -1, { 2, 6, 6, 4 } },
		{ "frost", "Hard frost", 0, false, 2, 0, { 0, 3, 8, 2 } },
		{ "thaw", "Thaw", 1, false, -1, 0, { 0, 0, 3, 6 } },
		{ "seafog", "Sea fog", 0, false, 0, -1, { 4, 5, 2, 5 } },
	};

	/** How hard the country is. Every knob the balance harness reads. */
	struct FHardshipRow
	{
		std::string Id;
		double Stir, Raid, Winter, Stores;
		int32_t Steel;
	};
	const std::vector<FHardshipRow> Hardships = {
		{ "fair", 0.6, 0.55, 0.7, 2.5, 1 },
		{ "even", 1, 1, 1, 1, 0 },
		{ "hard", 1.3, 1.35, 1.15, 0.7, -1 },
	};
	/** What `newGame` uses when the caller names no terms. */
	const std::string DefaultHardship = "even";
	inline const FHardshipRow& HardshipById(const std::string& Id)
	{
		for (const FHardshipRow& Row : Hardships) if (Row.Id == Id) return Row;
		for (const FHardshipRow& Row : Hardships) if (Row.Id == DefaultHardship) return Row;
		return Hardships[0];
	}

	/** Fixed places, IN SEEDING ORDER — seedPlaces walks this list. */
	struct FPlaceKindRow { std::string Id; std::vector<std::string> Ground; int32_t MinFromLanding; };
	const std::vector<FPlaceKindRow> PlaceKinds = {
		{ "monastery", { "shore" }, 6 },
		{ "town", { "shore", "valley", "meadow" }, 11 },
		{ "wreck", { "shore" }, 3 },
		{ "oreseam", { "bog", "hills", "mountains" }, 4 },
	};
	constexpr int32_t PlaceMaxFromLanding = 16;

	/** How far the band sees on day one — Seasons[0].Sight, named for stage 1. */
	constexpr int32_t SightOnDayOne = 3;
	constexpr int32_t LandmarkSight = 8;

	/** Stores off the knarr, before the country's terms multiply them. */
	constexpr int32_t StartFood = 24;
	constexpr int32_t StartFirewood = 8;

	// --- The day cycle (stage 5) ---

	/** How much of a night's fire is the hearth rather than the heads round it. */
	constexpr double HearthShare = 0.55;
	/** The band the firewood figures were tuned against. Six off the knarr. */
	constexpr int32_t BandBase = 6;

	/**
	 * Being born, and getting older — src/data/lineage.ts.
	 *
	 * A generation is sixteen years and a run is five, so nobody here grows UP:
	 * a child is a mouth, a lift to the band's heart, and a name the saga ends
	 * with. ChildAppetite is what one of them eats against a grown share.
	 */
	constexpr int32_t BirthCooldown = 90;
	constexpr double BirthOdds = 0.02;
	constexpr int32_t BirthFoodFloor = 40;
	constexpr double ChildAppetite = 0.5;
	constexpr int32_t BirthHeart = 8;
	constexpr int32_t BearingMin = 16;
	constexpr int32_t BearingMax = 44;
	/**
	 * What a death costs the steading for the children it leaves behind.
	 *
	 * Per orphaned child, off the BAND's heart rather than one person's — the
	 * kin grief beside it is the one who lost somebody, this is everyone
	 * looking at who is left. Emitted since 2026-08-21: it was the only lineage
	 * number the port did not carry, because the port's Mourn did the kin
	 * half and not this one, and five points of it was the last divergence in
	 * runs/long.json.
	 */
	constexpr int32_t OrphanGrief = 5;

	/**
	 * What a cold night gives you, IN PICK ORDER — pick() indexes this list.
	 */
	struct FIllnessRow
	{
		std::string Label;
		std::map<std::string, int32_t> Effect;
		int32_t Heals;
	};
	const std::vector<FIllnessRow> Illnesses = {
		{ "A cough that will not clear", { { "might", -1 } }, 14 },
		{ "Fever in the night", { { "spirit", -1 }, { "wits", -1 } }, 12 },
		{ "Frostbitten hands", { { "craft", -2 } }, 20 },
		{ "Something on the lungs", { { "might", -1 }, { "spirit", -1 } }, 18 },
	};
	/** What a body has to beat to come through a fireless night unharmed. */
	constexpr int32_t SicknessBaseDc = 9;

	/**
	 * Short commons — the winter lever, ported 2026-08-20.
	 *
	 * The band can choose to eat less. RationShare multiplies the mouths
	 * formula, HalfRationHeart is taken off morale every day it is kept, and
	 * the weakest is wounded every HalfRationToll lean days.
	 */
	constexpr double RationShare = 0.5;
	constexpr int32_t HalfRationHeart = 2;
	constexpr int32_t HalfRationToll = 10;
	/** How fast a mood moves toward where the day is pushing it. */
	constexpr double MoodDrift = 0.28;
	/** What each body past the roof's room takes off everyone's mood. */
	constexpr int32_t CrowdingBite = 5;
	/** How far a neighbour's standing creeps back toward indifference a day. */
	constexpr double RepDrift = 0.12;
	/** The road's base chance of interrupting you, and the quiet opening days. */
	constexpr double BaseEventChance = 0.19;
	constexpr int32_t SettlingInDays = 6;
	/** Winters stood before the run closes itself out. */
	constexpr int32_t LongLifeWinters = 5;
	/** Effort to row a hex of coast, and how far a day's rowing carries. */

	// --- The steading (stage 5, rung 3) ---

	/** Name parts. The SUFFIX is drawn first — see nameFor's draw order. */
	const std::vector<std::string> NameRoots = {
		"Rav",
		"Bjarn",
		"Ulf",
		"Stein",
		"Ask",
		"Eik",
		"Hval",
		"Orm",
		"Val",
		"Hrafn",
		"Grim",
		"Sval",
		"Thorn",
		"Fisk",
		"Elg",
	};
	/** Keyed by the measure a site is best at, in MEASURES order. */
	const std::map<std::string, std::vector<std::string>> NameSuffix = {
		{ "water", { "á", "brekka", "lind" } },
		{ "soil", { "stead", "garth", "akr" } },
		{ "timber", { "holt", "skog", "lund" } },
		{ "harbour", { "vík", "fjord", "nes" } },
		{ "defence", { "borg", "fell", "klif" } },
	};

	/** Ground that will take barley, by terrain. From src/sim/site.ts. */
	const std::map<std::string, int32_t> SoilByTerrain = {
		{ "ocean", 0 },
		{ "shore", 1 },
		{ "meadow", 3 },
		{ "forest", 1 },
		{ "hills", 1 },
		{ "mountains", 0 },
		{ "bog", 0 },
		{ "valley", 4 },
	};

	constexpr int32_t MeasureMax = 5;
	constexpr int32_t WaterFloor = 1;
	/** How close a neighbour may be before the ground is already somebody's. */
	constexpr int32_t ClanElbow = 2;
	constexpr int32_t ClanCallsEvery = 15;
	constexpr int32_t PlotRadius = 2;
	constexpr double ShelterSaves = 0.8;
	constexpr int32_t WatchMax = 6;
	constexpr double WatchDecay = 0.5;
	constexpr int32_t PatchShelterCap = 1;
	constexpr int32_t ShelterMax = 6;
	constexpr int32_t RaidEarliestDay = 12;
	/** Nothing comes for a place only just marked out. */
	constexpr int32_t RaidRespite = 14;
	constexpr double RaidChanceMax = 0.055;
	constexpr double ChancePerWorth = 0.0015;
	/** A coast with a grievance is a busier coast. */
	constexpr double PressureMax = 3;
	constexpr double PressurePerAnger = 0.035;
	constexpr double PressureStir = 0.3;
	/** What a stood watch buys in quiet, per point. */
	constexpr double WatchQuiet = 0.07;
	/** The day the dark closes in, and the day the telegraph stops warning. */
	constexpr int32_t WinterDay = 49;
	/** The winter mark: what it asks for over what it needs, and how vague it is. */
	constexpr double Prudence = 1.15;
	constexpr int32_t HazeClears = 20;
	constexpr int32_t HazeRange = 40;
	constexpr double HazeMax = 0.3;
	constexpr int32_t DrawLarderDays = 8;
	/** Somebody comes and asks; a sword comes looking for a share. */
	constexpr double DrawMax = 0.1;
	constexpr double DrawAnger = 0.8;
	constexpr double SwordMax = 0.055;
	constexpr int32_t SwordDeeds = 4;
	constexpr int32_t SwornMax = 6;
	/** Hands who have had enough, and go. The sworn never do. */
	constexpr int32_t LeavingMood = 25;
	constexpr double LeavingChance = 0.12;
	constexpr int32_t SettledIn = 30;
	/** What idleness costs the band's nerve, a head a day. */
	constexpr double IdleBite = 0.6;

	/** A job: what it reads, what it makes, and how much of it. */
	struct FJobRow
	{
		std::string Id, Stat, Measure, Produces;
		double Floor, PerPoint, Seasonal;
	};
	const std::vector<FJobRow> Jobs = {
		{ "farmer", "craft", "soil", "food", 0, 0.42, 1 },
		{ "hunter", "wits", "timber", "food", 0.5, 0.22, 0.7 },
		{ "fisher", "wits", "harbour", "food", 0.15, 0.38, 0.5 },
		{ "woodcutter", "might", "timber", "firewood", 0.2, 0.4, 0.45 },
		{ "builder", "craft", "timber", "shelter", 0.35, 0.18, 0.3 },
		{ "warrior", "might", "defence", "watch", 0.25, 0.14, 0 },
		{ "healer", "wits", "water", "care", 0.35, 0.3, 0 },
	};

	/** A measure and an amount — a building's needs or raises. */
	struct FMeasureRow { std::string Measure; int32_t Value; };

	/**
	 * A building. `Replaces`, `Repeat` and `Unlocks` are empty where the
	 * data left them out, which is how an absent field is spelled here.
	 */
	struct FBuildingRow
	{
		std::string Id;
		int32_t Timber, Works;
		double Shelter;
		int32_t Heart, Room;
		std::vector<std::string> After;
		std::vector<FMeasureRow> Needs, Raises;
		/** Multiplier on food work. 1 where the data left it out. */
		double FoodKeep;
		std::string Replaces, Repeat, Unlocks;
	};
	const std::vector<FBuildingRow> Buildings = {
		{ "longhouse", 6, 6, 3, 1, 6, {  }, {  }, {  }, 1, "", "", "" },
		{ "farmplots", 4, 5, 0, 0, 0, {  }, { { "soil", 1 } }, { { "soil", 1 } }, 1, "", "", "" },
		{ "smokehouse", 5, 4, 0, 0, 0, { "longhouse" }, {  }, {  }, 1.25, "", "", "" },
		{ "dock", 6, 5, 0, 0, 0, {  }, { { "harbour", 1 } }, { { "harbour", 1 } }, 1, "", "", "fisher" },
		{ "palisade", 8, 7, 0, 0, 0, {  }, { { "timber", 1 } }, { { "defence", 2 } }, 1, "", "", "" },
		{ "bud", 5, 4, 1, 0, 4, { "longhouse" }, {  }, {  }, 1, "", "crowded", "" },
		{ "meadhall", 7, 8, 1, 3, 3, { "longhouse" }, {  }, {  }, 1, "", "", "" },
		{ "storehouse", 5, 5, 0, 0, 0, { "smokehouse" }, {  }, {  }, 1.15, "", "", "" },
		{ "watchtower", 5, 5, 0, 0, 0, { "palisade" }, {  }, { { "defence", 2 } }, 1, "", "", "" },
		{ "greathall", 14, 11, 5, 2, 12, {  }, {  }, {  }, 1, "longhouse", "", "" },
		{ "earthworks", 12, 10, 0, 0, 0, {  }, { { "timber", 1 } }, { { "defence", 4 } }, 1, "palisade", "", "" },
		{ "hof", 7, 7, 0, 2, 0, { "meadhall" }, {  }, {  }, 1, "", "", "" },
	};
	inline const FBuildingRow* BuildingById(const std::string& Id)
	{
		for (const FBuildingRow& Row : Buildings) if (Row.Id == Id) return &Row;
		return nullptr;
	}

	/** Which jobs each kind of ground is worked by. */
	struct FPlotRow { std::string Kind; std::vector<std::string> Worked; };
	const std::vector<FPlotRow> Plots = {
		{ "hall", { "builder" } },
		{ "field", { "farmer" } },
		{ "wood", { "woodcutter", "hunter" } },
		{ "water", { "fisher" } },
		{ "rough", {  } },
		{ "watchpost", { "warrior" } },
	};

	constexpr int32_t SaveVersion = 59;
}
}
