// Generates the C++ header the port's event engine reads.
//
//   npm run event-tables
//
// Same bargain as scripts/party-tables.ts and for the same reason: the deck
// is authored in src/data/eventCards.ts and nowhere else, and the port must
// never become a second place to add a card. It is a separate header only
// because it is ninety kilobytes of prose — a card edit should not churn the
// file that holds names and constants.
//
// **Order is load-bearing.** `maybeFireEvent` filters EVENTS in declaration
// order and hands the survivors to `rng.weighted`, which walks them in that
// order subtracting weights until the roll goes negative. Reorder this list
// and every seed deals a different card. That is why it is generated.
//
// Optional fields are RESOLVED HERE rather than carried into C++ — `count`
// defaults to 1, `difficulty` and `n` where the kind allows it to 0 or 1 —
// so the interpreter has no defaulting of its own to get subtly wrong.

import { writeFileSync } from 'node:fs';
import { EVENTS } from '../src/data/eventCards';
import type { Condition, Effect, EventChoice, Outcome } from '../src/data/events';

const quote = (s: string): string => JSON.stringify(s);
const list = (values: readonly string[]): string => `{ ${values.map(quote).join(', ')} }`;

/**
 * A condition, flattened to four fields.
 *
 * Sixteen kinds carry at most one list, one number and one name between them,
 * so a tagged struct with those three beats sixteen structs or a variant. The
 * kind string stays the tag and the interpreter switches on it.
 */
function condition(c: Condition): string {
  const any = c.c === 'terrain' || c.c === 'season' ? (c as { any: string[] }).any : [];
  const num =
    c.c === 'dayMin' ? c.day
      : c.c === 'moraleMax' || c.c === 'foodMax' || c.c === 'firewoodMax' ? c.value
        : c.c === 'anger' || c.c === 'goodwill' ? c.min
          : 0;
  const text =
    c.c === 'flagSet' || c.c === 'flagUnset' ? c.flag
      : c.c === 'unknown' || c.c === 'known' ? c.lore
        : c.c === 'built' ? c.building
          : '';
  return `{ ${quote(c.c)}, ${list(any)}, ${num}, ${quote(text)} }`;
}

/** An effect, likewise — see the header's comment for which field is which. */
function effect(e: Effect): string {
  const num =
    e.t === 'reveal' ? e.radius
      : e.t === 'battle' || e.t === 'raid' ? (e.difficulty ?? 0)
        : e.t === 'join' ? (e.n ?? 1)
          : 'n' in e ? e.n
            : 0;
  const count = e.t === 'wound' ? (e.count ?? 1) : 1;
  const text =
    e.t === 'flag' ? e.flag
      : e.t === 'learn' ? e.lore
        : e.t === 'standing' ? e.who
          : e.t === 'join' ? e.why
            : '';
  return `{ ${quote(e.t)}, ${num}, ${count}, ${quote(text)} }`;
}

const outcome = (o: Outcome): string =>
  `{ ${quote(o.text)}, { ${o.effects.map(effect).join(', ')} } }`;

const EMPTY_OUTCOME = '{ "", {} }';

function choice(c: EventChoice): string {
  const check = c.check
    ? `true, ${quote(c.check.stat)}, ${c.check.dc}`
    : `false, "", 0`;
  const failure = c.failure ? `true, ${outcome(c.failure)}` : `false, ${EMPTY_OUTCOME}`;
  return `\t\t{ ${quote(c.label)}, ${check},\n`
    + `\t\t\t${outcome(c.success)},\n`
    + `\t\t\t${failure} },`;
}

const cards = EVENTS.map((e) => [
  `\t{ ${quote(e.id)}, ${quote(e.title)},`,
  `\t\t${quote(e.body)},`,
  `\t\t${e.weight}, ${e.once ? 'true' : 'false'},`,
  `\t\t{ ${(e.when ?? []).map(condition).join(', ')} },`,
  `\t\t{`,
  e.choices.map(choice).map((line) => line.replace(/^\t\t/gm, '\t\t\t')).join('\n'),
  `\t\t} },`,
].join('\n')).join('\n');

export function renderEventTables(): string {
  return `// GENERATED by scripts/event-tables.ts from src/data/eventCards.ts —
// do not hand-edit. Add a card there and re-run \`npm run event-tables\`.
//
// THE ORDER OF THIS LIST IS PART OF EVERY SEED. \`maybeFireEvent\` filters it
// in declaration order and \`rng.weighted\` walks the survivors subtracting
// weights until one roll goes negative, so moving a card moves what every
// seed deals. Nothing here may be sorted, deduplicated or held in a map.
//
// Optional fields are already resolved: \`count\` is 1 where the card left it
// out, \`difficulty\` is 0, \`join\`'s \`n\` is 1. The interpreter has no
// defaulting of its own, which is one fewer place for the two sides to
// disagree quietly.

#pragma once

#include <cstdint>
#include <string>
#include <vector>

namespace Landnam
{
namespace Tables
{
	/**
	 * One condition on a card, flattened.
	 *
	 * \`Any\` is the terrain or season list; \`Num\` is whichever number the kind
	 * carries (\`day\`, \`value\` or \`min\`); \`Text\` is whichever name it carries
	 * (\`flag\`, \`lore\` or \`building\`). Unused fields are empty or nought.
	 */
	struct FEventCondition
	{
		std::string C;
		std::vector<std::string> Any;
		int32_t Num;
		std::string Text;
	};

	/**
	 * One effect, flattened the same way.
	 *
	 * \`N\` is \`n\`, or \`radius\` for reveal, or \`difficulty\` for battle and
	 * raid. \`Count\` is wound's \`count\` and 1 everywhere else. \`Text\` is
	 * \`flag\`, \`lore\`, \`who\` or \`why\`, whichever the kind carries.
	 */
	struct FEventEffect
	{
		std::string T;
		int32_t N;
		int32_t Count;
		std::string Text;
	};

	struct FEventOutcome
	{
		std::string Text;
		std::vector<FEventEffect> Effects;
	};

	/** A choice. No check means it always succeeds; no failure reuses success. */
	struct FEventChoice
	{
		std::string Label;
		bool bHasCheck;
		std::string CheckStat;
		int32_t CheckDc;
		FEventOutcome Success;
		bool bHasFailure;
		FEventOutcome Failure;
	};

	struct FEventCard
	{
		std::string Id;
		std::string Title;
		std::string Body;
		int32_t Weight;
		/** Fires at most once a run, tracked by the \`seen_<id>\` flag. */
		bool bOnce;
		std::vector<FEventCondition> When;
		std::vector<FEventChoice> Choices;
	};

	const std::vector<FEventCard> Events = {
${cards}
	};
}
}
`;
}

// Writing is the CLI's job, not the module's. `test/tables.test.ts` imports
// renderEventTables to check the committed header is still what the data
// produces, and an import that wrote a file as a side effect would make that
// test pass by rewriting the very thing it is checking.
//
// Keyed on being GIVEN a path rather than on argv[0], because under vite-node
// argv[1] is vite-node itself — the obvious `endsWith('event-tables.ts')`
// guard is simply always false, and silently.
const out = process.argv.find((arg) => arg.endsWith('.h'));
if (out) {
  const text = renderEventTables();
  writeFileSync(out, text);
  // eslint-disable-next-line no-console
  console.log(
    `event-tables: wrote ${out} — ${EVENTS.length} cards, `
    + `${EVENTS.reduce((n, e) => n + e.choices.length, 0)} choices, ${text.length} chars`,
  );
}
