// Generates the C++ header the port's party generation reads.
//
//   npm run party-tables
//
// The content stays authored in src/data — this only restates it in a form a
// compiler can eat, exactly as ue-port's exporter restates terrain and foes
// as DataTables. The project's oldest architectural rule is that adding a
// name or a trait must never require touching engine code, and it still does
// not: add it in src/data/*.ts and re-run this.
//
// A generated HEADER rather than a JSON file, for one reason worth writing
// down. The sim core is deliberately free of Unreal so the identical
// translation unit compiles in a standalone harness that can be run against
// the parity vectors on any machine with a compiler — and that harness has no
// JSON parser and should not grow one. Stage 1 found two real bugs that way.
// A header needs nothing but the compiler.

import { writeFileSync } from 'node:fs';
import { MEN, WOMEN, BYNAMES, LANDING_NAMES } from '../src/data/names';
import { TRAITS } from '../src/data/traits';
import { ELDER_TIES, PEER_TIES } from '../src/data/kin';

const quote = (s: string): string => JSON.stringify(s);
const list = (name: string, values: readonly string[]): string =>
  `const std::vector<std::string> ${name} = {\n\t${values.map(quote).join(',\n\t')},\n};`;

const traits = TRAITS.map((t) =>
  `\t{ ${quote(t.id)}, ${t.stats.might ?? 0}, ${t.stats.wits ?? 0}, `
  + `${t.stats.spirit ?? 0}, ${t.stats.craft ?? 0} },`).join('\n');

/** PEER_TIES holds a LIST of pairs per key; a peer tie is drawn from it. */
const peerTies = (name: string, table: Record<string, readonly (readonly string[])[]>): string => {
  const rows = Object.entries(table)
    .map(([k, pairs]) => `\t{ ${quote(k)}, { ${pairs
      .map((p) => `{ ${quote(p[0]!)}, ${quote(p[1]!)} }`).join(', ')} } },`)
    .join('\n');
  return `const std::map<std::string, std::vector<std::pair<std::string, std::string>>> ${name} = {\n${rows}\n};`;
};

/** ELDER_TIES holds exactly ONE pair per key — parent and child, not a choice. */
const elderTies = (name: string, table: Record<string, readonly string[]>): string => {
  const rows = Object.entries(table)
    .map(([k, p]) => `\t{ ${quote(k)}, { ${quote(p[0]!)}, ${quote(p[1]!)} } },`)
    .join('\n');
  return `const std::map<std::string, std::pair<std::string, std::string>> ${name} = {\n${rows}\n};`;
};

const text = `// GENERATED by scripts/party-tables.ts from src/data — do not hand-edit.
// Add a name or a trait in src/data/*.ts and re-run \`npm run party-tables\`.
//
// Order matters and is load-bearing: every list here is drawn from with
// \`rng.pick(index)\`, so reordering one silently changes every warband ever
// rolled from every seed. That is why this is generated rather than retyped.

#pragma once

#include <map>
#include <string>
#include <utility>
#include <vector>

namespace Landnam
{
namespace Tables
{
\t${list('Men', MEN).replace(/\n/g, '\n\t')}

\t${list('Women', WOMEN).replace(/\n/g, '\n\t')}

\t${list('Bynames', BYNAMES).replace(/\n/g, '\n\t')}

\t${list('LandingNames', LANDING_NAMES).replace(/\n/g, '\n\t')}

\t/** A trait's stat nudge, applied once at generation. */
\tstruct FTraitRow { std::string Id; int Might, Wits, Spirit, Craft; };
\tconst std::vector<FTraitRow> Traits = {
${traits.replace(/^\t/gm, '\t\t')}
\t};

\t${elderTies('ElderTies', ELDER_TIES as never).replace(/\n/g, '\n\t')}

\t${peerTies('PeerTies', PEER_TIES as never).replace(/\n/g, '\n\t')}
}
}
`;

const out = process.argv[process.argv.length - 1];
const path = out.endsWith('.h') ? out : 'port/LandnamPartyTables.generated.h';
writeFileSync(path, text);
// eslint-disable-next-line no-console
console.log(
  `party-tables: wrote ${path} — ${MEN.length} men, ${WOMEN.length} women, `
  + `${BYNAMES.length} bynames, ${TRAITS.length} traits, ${LANDING_NAMES.length} landings`,
);
