// Generates the DataTable JSON the port's editor side reads.
//
//   npm run port-data
//
// FOURTH OF THE GENERATORS, and the only one written after the drift it
// prevents had already happened.
//
// `Content/Data/foes.json` in the port carried FOUR archetypes against this
// repo's eight — `spearman`, `bondi`, `wolfcoat` and `outlaw` were simply
// missing — and its row struct had no `Renown` column at all, so the knob
// that decides which foes a famous band meets could not have been imported
// even if the rows had been there.
//
// The cause is written on the file it drifted next to. `foe-names.json` says
// "Generated by ue-port/tools/export-data.mjs from src/data/foes.ts", and
// that script exists in neither repo any more. So these three files were
// generated once, the generator was lost, and after that they were whatever
// somebody last typed. Two of the three happened to still be right when this
// was written, and that is luck rather than a property — which is why all
// three are generated here rather than only the broken one.
//
// The C++ sim was never affected: it reads `Tables::FoeArchetypes` out of
// `port/LandnamBattleTables.gen.h`, which is generated, is under the port
// contract, and has had all eight all along. What drifted is the editor and
// Blueprint side, which is exactly the half no parity run can see.

import { writeFileSync } from 'node:fs';
import { FOE_ARCHETYPES, FOE_NAMES, FOE_BYNAMES, CHAMPION_BYNAMES } from '../src/data/foes';
import { ALL_TERRAINS, isLand, terrainDef } from '../src/data/terrain';

/**
 * UE's DataTable JSON: one space of indent, and a `Name` key carrying the row
 * name alongside the row's own fields.
 *
 * Matched to what the port already holds rather than chosen, so that the file
 * this generator did NOT need to fix — terrain.json — comes out byte-identical
 * to the one on disk. That equality is the proof the generator is right rather
 * than merely plausible, and test/portData.test.ts holds it.
 *
 * `foe-names.json` is the same data but NOT byte-identical, because its `note`
 * named a generator that no longer exists in either repo and now names this
 * one. Its three arrays are checked instead.
 */
function asTable(rows: Record<string, unknown>[]): string {
  return `${JSON.stringify(rows, null, 1)}\n`;
}

export function foeRows(): Record<string, unknown>[] {
  return FOE_ARCHETYPES.map((foe) => ({
    Name: foe.id,
    Id: foe.id,
    Kind: foe.kind,
    Budget: foe.budget,
    Favours: foe.favours,
    Toughness: foe.toughness,
    Temperament: foe.temperament,
    Throws: foe.throws,
    Weight: foe.weight,
    // The column the port's row struct did not have. Adding a foe has been a
    // one-file job in this repo since `renown` moved out of sim/word.ts; it
    // was not one in the port, because the port could not see this number.
    Renown: foe.renown,
  }));
}

export function terrainRows(): Record<string, unknown>[] {
  return ALL_TERRAINS.map((id) => {
    const def = terrainDef(id);
    return {
      Name: id,
      Id: id,
      DisplayName: def.name,
      // Infinity does not survive JSON, and the port already reads -1 as
      // "impassable on foot". Keeping that convention rather than inventing
      // a new one: the file on disk is the contract.
      Cost: Number.isFinite(def.cost) ? def.cost : -1,
      Forage: def.forage,
      Hunt: def.hunt,
      Fish: def.fish,
      Wood: def.wood,
      bBlocksSight: def.blocksSight,
      bIsLand: isLand(id),
      Fill: def.fill,
      Edge: def.edge,
    };
  });
}

export function foeNames(): Record<string, unknown> {
  return {
    note: 'Generated by scripts/port-data.ts from src/data/foes.ts. Not a DataTable.',
    FoeNames: FOE_NAMES,
    FoeBynames: FOE_BYNAMES,
    ChampionBynames: CHAMPION_BYNAMES,
  };
}

function main(): void {
  writeFileSync('port/foes.json', asTable(foeRows()));
  writeFileSync('port/terrain.json', asTable(terrainRows()));
  writeFileSync('port/foe-names.json', `${JSON.stringify(foeNames(), null, 1)}\n`);
  // eslint-disable-next-line no-console
  console.log(
    `port-data — ${foeRows().length} foes, ${terrainRows().length} terrains, `
      + `${FOE_NAMES.length}/${FOE_BYNAMES.length}/${CHAMPION_BYNAMES.length} names`,
  );
}

main();
